### ISSUE TITLE
Move talents from semi-cursed branch to dragonflight

### ISSUE THREAD

**Issue by seanpeters86** [WarcraftPriests/df-shadow-priest#1]
Completed:
- [x] Shadowfiend
- [x] Improved Shadowfiend
- [x] Mindbender
- [x] Rabid Shadows
- [x] Shadowflame Prism
- [x] Mindgames
- [x] Shadow Mend
- [x] Shadow Mend push back
- [x] Shadow Word: Death
- [x] Masochism
- [x] Taming the Shadows
- [x] Mind Blast
- [x] Improved Mind Blast
- [x] Power Infusion
- [x] Twist of Fate
- [x] Tithe Evasion
- [x] Translucent Image
- [x] Idol of C'Thun
- [x] Void Apparitions
- [x] Psychic Horror
- [x] Eidolic Insight basic impl. with empirical data
- [x] Hallucinations
- [x] Vampiric Embrace
- [x] Mind Bomb

TODOs:
- [ ] Twist of Fate data is turbo fucked
- [ ] Dominant Mind "fake" support for Puppet Master
- [ ] Power Infusion Mindbender/etc with Twins talented
- [ ] Translucent Image has no scaling data, always give 5% DR
- [ ] Make sure i didnt break Psychic Link
- [ ] Psychic Scream + Psychic Voice
- [ ] Intangibility + Dispersion Healing
- [ ] Power Word: Shield absorb value is very wrong
- [ ] Determine actual proc rates for VI and EI. Using ~10m log data to approx at the moment
- [x] [Finish Living Shadow](https://github.com/simulationcraft/simc/pull/6608)

**Comment by Saeldur** [comment]
Completed:
- [x] Mind Flay
- [x] Vampiric Touch
- [x] Devouring Plague
- [x] Mind Sear
- [x] Death and Madness
- [x] Mind Bomb
- [ ] Psychic Voice
- [x] Misery & SN
- [x] Silence
- [x] Fortress of the Mind
- [x] Vampiric Embrace
- [x] Unfurling Darkness
- [x] Vampiric Insight
- [x] Last Word
- [x] Dispersion
- [x] San'Layn
- [x] Hallucinations
- [x] Shadowy Apparitions
- [x] Void Eruption
- [x] Monomania
- [x] Psychic Horror
- [ ] Intangibility
- [x] Psychic Link
- [x] Auspicious Spirits
- [x] STM
- [x] HV
- [x] Damnation
- [x] Void Touched
- [x] Shadow Crash
- [x] Ancient Madness
- [x] Malediction
- [x] Void Torrent
- [x] Mental Fortitude
- [x] Insidious Ire
- [x] Mind Devourer
- [x] Sanguine Teachings
- [x] Unleash the Shadows
- [x] Rot and Wither
- [x] Abyssal Knowledge
- [x] Idol of Y'shaarj
- [x] Idol of N'zoth
- [x] Void Apparitions
- [x] Living Shadow
- [x] Eidolic Intuition
- [x] Idol of C'thun
- [x] Idol of Yogg-Saron
- [x] Throes of Pain
- [x] Puppet Master


TODO:
- [ ] Solve Mind Devourer TODO in implementation
- [ ] Fix VT/DP to not cheat in implementation
- [x] Mind Devourer buff?
- [ ] Check SN works properly
- [ ] Check D&M after death added
- [ ] Vampiric Insight TODO - Ask devs how it works or test for hours. 
- [x] Vampiric Insight buff whitelist 375981
- [x] Look into PL, wasn't working at all despite being implemented.
- [x] stop HV using .spell()
- [ ] Check Void Touched + Dissonant echoes interaction prepatch
- [x] Whitelist Void Touched 373375 and use the actual spell id.
- [x] Add demise stuff for throes of pain
- [ ] Add throes of pain to discipline priest
- [ ] Change mental fort to ->percent() after it gets an entry or base changes
- [ ] Check more yogg stuff, stack/extend behaviour after they fix it
- [ ] Check nzoth keeps using the same driver setup
- [ ] Give Y'Shaarj Spell Data when implemented.

**Comment by seanpeters86** [comment]
moved to https://github.com/WarcraftPriests/df-shadow-priest/issues/3
